---
    title: "Untitled"
output: html_document
---
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r base_data}
library(tidyverse)
options(scipen = 999)

df_sound <-
    tibble(unit = c(1:19, 
                    seq(20, 90, by = 10)),
           #1e3, 1e4, 1e5, 1e6),
           sound = c("one", "two", "three", "four", "five", 
                     "six", "se-ven", "eight", "nine", "ten",
                     "e-le-ven", "twel-ve", "thir-teen", "four-teen", "fif-teen", 
                     "six-teen", "sev-en-teen", "eight-teen", "nine-teen",
                     "twen-ty", "thir-ty", "four-ty", "fif-ty",
                     "six-ty", "seven-ty", "eigh-ty", "nine-ty"))
```


```{r all_nums}
all_nums <-
    tibble(number = 1:1e6) %>% 
    #slice(1:100) %>% 
    mutate(d7 = str_sub(number, -7, -7),
           d6 = str_sub(number, -6, -6),
           d5 = case_when((str_sub(number, -5, -4) >= 10 & 
                               str_sub(number, -5, -4) < 20) ~ str_sub(number, -5, -4),
                          TRUE ~ paste0(str_sub(number, -5, -5), 0)),
           d4 = case_when((str_sub(number, -5, -4) >= 10 & str_sub(number, -5, -4) < 20) ~ "0",
                          TRUE ~ str_sub(number, -4, -4)),
           d3 = str_sub(number, -3, -3),
           d2 = case_when((str_sub(number, -2) >= 10 & str_sub(number, -2) < 20) ~ str_sub(number, -2),
                          TRUE ~ paste0(str_sub(number, -2, -2), 0)),
           d1 = case_when((str_sub(number, -2) >= 10 & str_sub(number, -2) < 20) ~ "0",
                          TRUE ~ str_sub(number, -1))) %>% 
    mutate_all(as.integer) %>% 
    mutate(t7 = ifelse(is.na(d7), "", "one mill-i-on"))

get_joins <-
    all_nums %>% 
    left_join(df_sound %>% mutate(sound6 = paste(sound, "hund-red")) %>% select(unit, sound6), by = c("d6" = "unit")) %>% 
    left_join(df_sound %>% select(unit, sound5 = sound), by = c("d5" = "unit")) %>% 
    left_join(df_sound %>% select(unit, sound4 = sound), by = c("d4" = "unit")) %>% 
    left_join(df_sound %>% mutate(sound3 = paste(sound, "hund-red")) %>% select(unit, sound3), by = c("d3" = "unit")) %>% 
    left_join(df_sound %>% select(unit, sound2 = sound), by = c("d2" = "unit")) %>% 
    left_join(df_sound %>% select(unit, sound1 = sound), by = c("d1" = "unit"))

get_joins[5,]

```

```{r combine_text}
combine_text <-
    get_joins %>% 
    replace_na(list(sound6 = "",
                    sound5 = "",
                    sound4 = "",
                    sound3 = "",
                    sound2 = "",
                    sound1 = "")) %>% 
    mutate(t_100k = paste(sound6, sound5, sound4) %>% trimws(),
           t_100 = paste(sound3, sound2, sound1) %>% trimws()) %>% 
    mutate(t_100k = ifelse(t_100k == "", "", paste(t_100k, "thous-and")),
           final = 
               paste(t_100k, t_100) %>% 
               trimws(),
           count = str_count(final, "\\s|-") + 1)
```

```{r stats}

combine_text %>% 
    select(number:d1, #t_100k, t_100, 
           final, count) %>% 
    #slice(1:1000000) %>% 
    .$count %>% #log() %>% 
    hist()

# syllables per second
sps <- ceiling(sum(combine_text$count[1:100])/60)

#totals
sum(combine_text$count[1:100])/sps # 100 = 274 syllables in 60 seconds, 11 syllables a second
sum(combine_text$count[1:1e3])/sps/60 # 1K = 5513 syllables in 18.7 min
sum(combine_text$count[1:1e4])/sps/60/60 # 10K = 83103 syllables in 4.7 hours
sum(combine_text$count[1:1e5])/sps/60/60 # 100K = 1,020,005 syllables in 57 hours
sum(combine_text$count[1:1e6])/sps/60/60/24 # 1M = 13,018,000 syllables in 329 hours or 30.5 days

# 1 min rest for every 5 min of speaking, max 8 hours a day
(sum(combine_text$count[1:1e6])/sps/60 # total min (44K min)
    * 19/17 # 1 breath every 17 seconds (49K min)
    * (6/5) # 6 min for every 5 (59K min)
    / 60    # convert to hours (982 hours)
    / 8     # max 8 hours per day (122.8 days)
    * 7/5   # weekends off (170.8 days)
)
```
